### ISSUE TITLE
Apertura allegati compressi

### ISSUE THREAD

**Issue by elems** [abaldoni/vFattura#1]
Innanzi tutto grazie per l'applicazione vFattura, 
scusami ma non ho mai utilizzato github.
Volevo solo segnalare che se in allegato c'è un pdf compresso con zip, viene salvato con estensione pdf invece che con estensione zip. Quindi non viene aperto dal reader pdf.
Per ora mi sono capitati solo allegati in pdf e zip e ho risolto modificando il tuo codice aggiungendo una if nel caso in cui il nodo "AlgoritmoCompressione" è valorizzato. Se valorizzato utilizzo il valore inserito come estensione.
vFattura/Styler/vFatturaForm.cs
riga 148

```
if (attachment["FormatoAttachment"] != null)
            {
                if (attachment["AlgoritmoCompressione"] != null)
                {
                    fileName = System.IO.Path.GetTempPath() + Guid.NewGuid().ToString() + "." + attachment["AlgoritmoCompressione"].InnerText.ToLower().Trim();
                }
                else
                {
                    fileName = System.IO.Path.GetTempPath() + Guid.NewGuid().ToString() + "." + attachment["FormatoAttachment"].InnerText.ToLower().Trim();

                }
            }
            else
            {
                fileName = System.IO.Path.GetTempPath() + Guid.NewGuid().ToString() + attachment["NomeAttachment"].InnerText.Trim();
            }
```

**Comment by abaldoni** [comment]
Grazie @elems, ho inserito le tue modifiche nella versione 1.3.0.0 che recepisce il nuovo formato 1.2
